#!/usr/bin/env python
import tempfile
import os
import stat
import sys
import glob

def error(msg):
  print >> sys.stderr, '\033[1;31m%s\033[0m' % msg

def success(msg):
  print >> sys.stderr, '\033[1;32m%s\033[0m' % msg

def log(msg):
  pass
  print >> sys.stderr, '\033[0;37m  %s\033[0m' % msg

def die(msg):
  error(msg)
  sys.exit(1)

def check_make(src_files):
  # ensure the required files exist
  for f in src_files:
    src = os.path.join(SRC, f)
    if not os.path.exists(src):
      die('Could not find required file "%s"!' % f)
    log('found required file "%s"' % f)
    os.system('cp %s %s' % (src, DEST))

def do_submit(src_files):
  log('creating tarball for submission ...')
  tarball = '%s.tbz2' % USER
  exit = os.system('tar jcvf %s %s &> .out' % (tarball, ' '.join(src_files)))
  if exit != 0:
    die('Failed to create tarball for submission!')
  os.chmod(os.path.join(DEST, tarball), stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)
  log('submitting assignment ...')
  exit = os.system('/local/etc/bin/sgbit /usr/staff/comp2129/bin/submit-assignment assignment1 %s/%s' % (DEST, tarball))
  if exit != 0:
    die('Failed to submit assignment!')


if __name__ == '__main__':
  USER = os.getlogin()
  SRC  = os.getcwd()
  DEST = tempfile.mkdtemp()
  os.chmod(DEST, stat.S_IRWXU | stat.S_IXGRP | stat.S_IXOTH)

  SRC_FILES = ('find_repos.sh', 'grep_printer.sh', 'init.sh', 'run_tests.sh', 'version.sh', '.user')

  try:
    os.chdir(DEST)
    check_make(SRC_FILES)
    do_submit(SRC_FILES)

    success('Assignment successfully submitted.')
  finally:
    os.chdir(SRC)
    os.system('rm -rf %s' % DEST)

